name: GetInput
on:
  workflow_call:
  workflow_dispatch:

jobs:
  PrintLine:
    runs-on: [self-hosted, linux, X64, linuxrunner]

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Production deployment
        shell: bash
        run: |
          echo "doing prodcution deployment"
          echo "GITHUB_REPOSITORY is $GITHUB_REPOSITORY" 
    
